import { C_Dashboard } from "../global/constants";

export const styles = {
  page: {
    minHeight: "100vh",
    background: C_Dashboard.pageBg,
    fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif',
    color: C_Dashboard.ink,
    paddingBottom: 64,
  },
  topBar: {
    background: "#fff",
    borderBottom: `1px solid ${C_Dashboard.border}`,
    padding: "0 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 54,
    position: "sticky",
    top: 0,
    zIndex: 200,
    boxShadow: "0 1px 3px rgba(20,40,70,0.06)",
  },
  logo: { height: 26, objectFit: "contain" },
  brandRow: { display: "flex", alignItems: "center", gap: 7 },
  brand: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: C_Dashboard.brand,
  },
  dashboardTitle: { fontSize: 13, fontWeight: 600 },
  pageHeader: { maxWidth: 1120, margin: "0 auto", padding: "28px 16px 0" },
  pageHeading: {
    fontSize: 21,
    fontWeight: 700,
    margin: "0 0 4px",
    letterSpacing: -0.3,
  },
  pageCaption: { fontSize: 13, color: C_Dashboard.muted, margin: 0 },
  filterRow: {
    background: "#fff",
    borderRadius: 14,
    border: `1px solid ${C_Dashboard.border}`,
    padding: "14px 18px",
    marginBottom: 20,
    boxShadow: "0 1px 3px rgba(20,40,70,0.05)",
  },
  filter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    flexWrap: "wrap",
    gap: 8,
  },
  filterTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: C_Dashboard.muted,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  sortRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  clearBtn: {
    fontSize: 11,
    fontWeight: 600,
    color: C_Dashboard.brand,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  filterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))",
    gap: 10,
  },
  filterLabelRow: { display: "flex", flexDirection: "column", gap: 4 },
  filterLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: C_Dashboard.muted,
  },
  responseCount: {
    fontSize: 12,
    color: C_Dashboard.muted,
    margin: "0 0 14px",
  },
  errorContainer: {
    background: "#fff",
    borderRadius: 14,
    border: `1px solid ${C_Dashboard.border}`,
    padding: "40px 24px",
    textAlign: "center",
  },
  errorText: { color: C_Dashboard.red, fontSize: 13, margin: 0 },
  emptyStateContainer: {
    background: "#fff",
    borderRadius: 14,
    border: `1px solid ${C_Dashboard.border}`,
  },
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(300px,1fr))",
    gap: 14,
  },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    flexWrap: "wrap",
    gap: 10,
  },
  pageText: { fontSize: 12, color: C_Dashboard.muted },
};
