export const styles = {
  page: {
    minHeight: "100vh",
    backgroundColor: "#EEF1F8",
    fontFamily:
      "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    padding: "0",
    margin: "0",
  },

  // ─── Top bar ───────────────────────────────────────────────
  topBar: {
    backgroundColor: "#ffffff",
    borderBottom: "1px solid #e2e6f0",
    padding: "0 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "56px",
    gap: "12px", // prevents items from colliding on narrow screens
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexShrink: 0, // logo + title never compress
  },
  topBarCenter: {
    flex: 1, // absorbs available space between left and right
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0, // allows text-overflow to engage
    overflow: "hidden",
  },
  topBarRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "8px",
  },
  topBarDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    backgroundColor: "#3B5BDB",
    flexShrink: 0,
  },
  topBarTitle: {
    fontSize: "15px",
    fontWeight: "600",
    color: "#1a2340",
    margin: 0,
    whiteSpace: "nowrap",
  },
  topBarPeriod: {
    fontSize: "14px",
    color: "#3B5BDB",
    fontWeight: "500",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  navBtn: {
    padding: "8px 18px",
    borderRadius: 8,
    border: "1px solid #3B5BDB",
    background: "transparent",
    color: "#3B5BDB",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    flexShrink: 0, // never shrink the nav button
    whiteSpace: "nowrap",
  },
  logoutBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "8px 16px",
    borderRadius: 8,
    border: "1px solid #b3261e",
    background: "#fff",
    color: "#b3261e",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    transition: "background 0.15s, border-color 0.15s",
  },

  // ─── Content ───────────────────────────────────────────────
  contentWrapper: {
    maxWidth: "760px",
    margin: "0 auto",
    padding: "20px 20px 60px",
  },
  card: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: "16px",
    borderTopRightRadius: "16px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)",
    overflow: "hidden",
  },
  cardHeader: {
    // fluid padding: generous on desktop, tighter on mobile (set via className + CSS)
    padding:
      "clamp(18px, 4vw, 25px) clamp(16px, 5vw, 40px) clamp(5px, 4vw, 5px)",
    textAlign: "center",
  },
  cardTitle: {
    fontSize: "20px",
    fontWeight: "700",
    color: "#1a2340",
    margin: "0 0 2px",
    fontFamily: "inherit",
  },
  cardSubtitle: {
    fontSize: "14px",
    color: "#6b7898",
    margin: 0,
    lineHeight: "1.6",
  },
  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "clamp(16px, 3vw, 20px) clamp(16px, 5vw, 40px) 0",
  },
  sectionBadge: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    backgroundColor: "#3B5BDB",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: "700",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#1a2340",
    margin: 0,
  },
  formBody: {
    padding:
      "clamp(12px, 3vw, 15px) clamp(16px, 5vw, 40px) clamp(24px, 5vw, 36px)",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
    backgroundColor: "#e2e8f7",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  // fieldRow: {
  //   flexDirection:'row'
  // },
  label: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#3d4f7c",
    letterSpacing: "0.01em",
    textAlign: "left",
  },
  input: {
    height: "35px",
    borderRadius: "10px",
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "#dde3f0",
    borderRadius: "10px",
    padding: "0 14px",
    fontSize: "12px",
    color: "#1a2340",
    backgroundColor: "#fafbfd",
    outline: "none",
    transition: "border-color 0.15s, box-shadow 0.15s",
    width: "100%",
    boxSizing: "border-box",
  },
  inputFocus: {
    borderColor: "#3B5BDB",
    boxShadow: "0 0 0 3px rgba(59,91,219,0.12)",
    backgroundColor: "#ffffff",
  },
  row: {
    display: "grid",
    // collapses to 1 col below ~360px naturally; for explicit mobile override use className
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: "16px",
  },
  select: {
    height: "35px",
    borderRadius: "10px",
    borderWidth: "1.5px",
    borderStyle: "solid",
    borderColor: "#dde3f0",
    padding: "0 36px 0 14px",
    fontSize: "12px",
    color: "#1a2340",
    backgroundColor: "#fafbfd",
    outline: "none",
    appearance: "none",
    WebkitAppearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%236b7898' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
    transition: "border-color 0.15s, box-shadow 0.15s",
    width: "100%",
    boxSizing: "border-box",
    cursor: "pointer",
  },
  selectFocus: {
    borderColor: "#3B5BDB",
    boxShadow: "0 0 0 3px rgba(59,91,219,0.12)",
    backgroundColor: "#ffffff",
  },
  divider: {
    height: "0.5px",
    backgroundColor: "transparent",
    margin: "0px 0",
  },
  generateBtn: {
    height: "38px",
    borderRadius: "10px",
    border: "none",
    backgroundColor: "#3B5BDB",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    transition: "background-color 0.15s, transform 0.1s",
    letterSpacing: "0.01em",
    marginTop: "4px",
    width: "50%",
    alignSelf: "center",
  },
  generateBtnHover: { backgroundColor: "#2f4abf" },
  generateBtnActive: { transform: "scale(0.98)" },
  resultBox: {
    backgroundColor: "#f0f4ff",
    border: "1.5px solid #c7d2f8",
    borderRadius: "10px",
    padding: "10px 12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginTop: "4px",
    flexWrap: "wrap", // URL + copy button wrap on very narrow screens
  },
  resultUrl: {
    fontSize: "12px",
    color: "#3B5BDB",
    fontWeight: "500",
    wordBreak: "break-all",
    flex: 1,
    minWidth: "120px", // prevents the URL collapsing to zero before wrapping
    textDecoration: "none",
  },
  copyBtn: {
    flexShrink: 0,
    height: "32px",
    minWidth: "70px",
    borderRadius: "8px",
    border: "1.5px solid #3B5BDB",
    backgroundColor: "transparent",
    color: "#3B5BDB",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    padding: "0 10px",
    transition: "background-color 0.15s",
  },
  copyBtnCopied: {
    backgroundColor: "#3B5BDB",
    color: "#ffffff",
  },

  // ─── History ───────────────────────────────────────────────
  historySection: {
    padding: "0 clamp(16px, 5vw, 40px) clamp(24px, 5vw, 36px)",
  },
  historyTitle: {
    fontSize: "13px",
    fontWeight: "700",
    color: "#6b7898",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: "12px",
  },
  historyItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderRadius: "10px",
    border: "1px solid #edf0f7",
    backgroundColor: "#ffffff",
    marginBottom: "8px",
    gap: "12px",
    flexWrap: "wrap", // actions wrap below info on very narrow screens
  },
  historyInfo: {
    flex: 1,
    minWidth: 0, // allows text to truncate rather than overflow
  },
  historyName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#1a2340",
    margin: "0 0 2px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  historyMeta: {
    fontSize: "12px",
    color: "#6b7898",
    margin: 0,
  },
  historyLink: {
    fontSize: "12px",
    color: "#3B5BDB",
    textDecoration: "none",
    fontWeight: "500",
  },
  historyActions: {
    display: "flex",
    gap: "6px",
    flexShrink: 0,
  },
  iconBtn: {
    width: "30px",
    height: "30px",
    borderRadius: "7px",
    border: "1px solid #dde3f0",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#6b7898",
    transition: "border-color 0.15s, color 0.15s",
  },
  addNewBtn: {
    height: "44px",
    borderRadius: "10px",
    border: "1.5px dashed #c7d2f8",
    backgroundColor: "#f7f9ff",
    color: "#3B5BDB",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "background-color 0.15s",
    marginBottom: "4px",
  },

  // ─── Misc ──────────────────────────────────────────────────
  errorMsg: {
    fontSize: "12px",
    color: "#c0392b",
    marginTop: "2px",
    textAlign: "left",
  },
  toast: {
    position: "fixed",
    top: "28px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#1a2340",
    color: "#ffffff",
    padding: "10px 20px",
    borderRadius: "10px",
    fontSize: "13px",
    fontWeight: "500",
    zIndex: 1000,
    pointerEvents: "none",
    opacity: 1,
    transition: "opacity 0.3s",
  },

  // tab-styles
  strip: {
    display: "flex",
    borderTop: "1px solid #edf0f7",
    marginTop: 4,
  },
  tab: {
    flex: 1,
    padding: "12px 0",
    fontSize: "14px",
    fontWeight: "600",
    color: "#6b7898",
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    cursor: "pointer",
    transition: "color 0.15s, border-color 0.15s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  tabActive: {
    color: "#3B5BDB",
    borderBottom: "2px solid #3B5BDB",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    borderRadius: "50%",
    backgroundColor: "#3B5BDB",
    color: "#ffffff",
    fontSize: 11,
    fontWeight: 700,
  },
};
